/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package leyplusvalia;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;

/**
 * 
 * @author Bryan Molina M
 */
public class JFmain extends javax.swing.JFrame {

    /**
     * Creates new form JFmain
     */
    public JFmain() {
        initComponents();
        this.setLocationRelativeTo(null);
        txt_SBU.setHorizontalAlignment(SwingConstants.RIGHT);
        txt_TasaPasivaBCE.setHorizontalAlignment(SwingConstants.RIGHT);
        txt_FranjaExenta.setHorizontalAlignment(SwingConstants.RIGHT);
        txt_tiempoAnios.setHorizontalAlignment(SwingConstants.RIGHT);
        txt_tiempoMeses.setHorizontalAlignment(SwingConstants.RIGHT);
        txt_valorCosto.setHorizontalAlignment(SwingConstants.RIGHT);
        txt_valorMejoras.setHorizontalAlignment(SwingConstants.RIGHT);
        txt_valorContribucionesEspeciales.setHorizontalAlignment(SwingConstants.RIGHT);
        txt_valorVenta.setHorizontalAlignment(SwingConstants.RIGHT);

        panel_paso1.setVisible(false);
        panel_paso2.setVisible(false);
        panel_paso3.setVisible(false);
        jPanel4.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_SBU = new javax.swing.JTextField();
        txt_TasaPasivaBCE = new javax.swing.JTextField();
        txt_FranjaExenta = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_tiempoAnios = new javax.swing.JTextField();
        txt_tiempoMeses = new javax.swing.JTextField();
        txt_valorCosto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_valorMejoras = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_valorContribucionesEspeciales = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_valorVenta = new javax.swing.JTextField();
        btn_calcular = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        panel_paso2 = new javax.swing.JPanel();
        txt_paso2_ValorBien = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txt_paso2_FA = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lbl_paso2 = new javax.swing.JLabel();
        btn_paso3 = new javax.swing.JButton();
        panel_paso1 = new javax.swing.JPanel();
        txt_paso1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        btn_paso2 = new javax.swing.JButton();
        panel_paso3 = new javax.swing.JPanel();
        txt_paso3_ValorBienConIntereses = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txt_paso3_FranjaExenta = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        lbl_paso3 = new javax.swing.JLabel();
        lbl_paso4 = new javax.swing.JLabel();
        lbl_paso5 = new javax.swing.JLabel();
        txt_paso3_valorVenta = new javax.swing.JTextField();
        txt_paso3_gananciaOrdinaria = new javax.swing.JTextField();
        lbl_paso3_valorExtra = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        lbl_paso3_impuestoTOTAL = new javax.swing.JLabel();
        lbl_paso3_valorExtra2 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simulación Ley Plusvalía");

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel1.setText("Ley Orgánica Especulacion sobre Valor de las Tierras");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Parámetros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel2.setText("SBU:");

        jLabel3.setText("Tasa Pasiva BCE:");

        jLabel4.setText("Franja Exenta:");

        txt_SBU.setText("375");

        txt_TasaPasivaBCE.setText("7.38");

        txt_FranjaExenta.setText("9000");

        jLabel19.setText("i");

        jLabel17.setText("24 sueldos básicos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_FranjaExenta, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                            .addComponent(txt_TasaPasivaBCE)
                            .addComponent(txt_SBU))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txt_SBU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_TasaPasivaBCE, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_FranjaExenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel5.setText("Tiempo transcurrido entre compra venta");

        jLabel6.setText("Valor de costo de bien (escritura):");

        jLabel7.setText("Valor de mejoras y/o adecuaciones:");

        txt_tiempoAnios.setText("3");
        txt_tiempoAnios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tiempoAniosActionPerformed(evt);
            }
        });

        txt_tiempoMeses.setText("0");

        txt_valorCosto.setText("85000");

        jLabel8.setText("años");

        txt_valorMejoras.setText("15000");

        jLabel9.setText("Valor por contribuciones especiales de mejora:");

        txt_valorContribucionesEspeciales.setText("0");

        jLabel10.setText("Valor que estima vender:");

        txt_valorVenta.setText("0");

        btn_calcular.setText("Calcular");
        btn_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcularActionPerformed(evt);
            }
        });

        jLabel12.setText("meses");

        jLabel13.setText("A");

        jLabel14.setText("B");

        jLabel15.setText("C");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_tiempoAnios, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_tiempoMeses, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addGap(94, 94, 94))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(71, 71, 71)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(txt_valorCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(txt_valorMejoras, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10))
                                        .addGap(24, 24, 24)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txt_valorContribucionesEspeciales, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_valorVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(btn_calcular))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(txt_tiempoAnios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tiempoMeses, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_valorCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_valorMejoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_valorContribucionesEspeciales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_valorVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_calcular)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Resultado:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        panel_paso2.setBorder(javax.swing.BorderFactory.createTitledBorder("Paso2: Valor del BIen * Factor Ajuste"));

        jLabel18.setText("FA = ( 1 + i ) ^ n ");
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });

        jLabel20.setText("*");

        jLabel21.setText("Valor total del bien con intereses");

        lbl_paso2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_paso2.setForeground(new java.awt.Color(51, 0, 204));
        lbl_paso2.setText("Valor total del bien con intereses");

        btn_paso3.setText("Paso3");
        btn_paso3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_paso3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_paso2Layout = new javax.swing.GroupLayout(panel_paso2);
        panel_paso2.setLayout(panel_paso2Layout);
        panel_paso2Layout.setHorizontalGroup(
            panel_paso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_paso2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_paso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_paso2Layout.createSequentialGroup()
                        .addComponent(lbl_paso2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panel_paso2Layout.createSequentialGroup()
                        .addGroup(panel_paso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_paso2Layout.createSequentialGroup()
                                .addGroup(panel_paso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel21))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_paso2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txt_paso2_ValorBien, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_paso2_FA, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_paso2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_paso3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel_paso2Layout.setVerticalGroup(
            panel_paso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_paso2Layout.createSequentialGroup()
                .addComponent(jLabel18)
                .addGap(13, 13, 13)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_paso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_paso2_FA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_paso2_ValorBien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_paso2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btn_paso3))
        );

        panel_paso1.setBorder(javax.swing.BorderFactory.createTitledBorder("Paso1: Sumar A + B + C"));

        txt_paso1.setEditable(false);

        jLabel16.setText("Valor del bien:");

        btn_paso2.setText("Paso2");
        btn_paso2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_paso2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_paso1Layout = new javax.swing.GroupLayout(panel_paso1);
        panel_paso1.setLayout(panel_paso1Layout);
        panel_paso1Layout.setHorizontalGroup(
            panel_paso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_paso1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(txt_paso1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(panel_paso1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_paso1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_paso2))
        );
        panel_paso1Layout.setVerticalGroup(
            panel_paso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_paso1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_paso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_paso2))
        );

        panel_paso3.setBorder(javax.swing.BorderFactory.createTitledBorder("Paso 3:"));

        txt_paso3_ValorBienConIntereses.setEditable(false);

        jLabel22.setText("Valor del bien con iinteres + Franja Exenta:");

        txt_paso3_FranjaExenta.setEditable(false);

        jLabel23.setText("+");

        jLabel25.setText("=");

        lbl_paso3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_paso3.setForeground(new java.awt.Color(51, 0, 204));
        lbl_paso3.setText("Valor total del bien con intereses");

        lbl_paso4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_paso4.setForeground(new java.awt.Color(51, 0, 204));
        lbl_paso4.setText("Ganancia ORDINARIA");

        lbl_paso5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_paso5.setForeground(new java.awt.Color(255, 0, 51));
        lbl_paso5.setText("G. EXTRAORDINARIA");

        txt_paso3_valorVenta.setEditable(false);

        txt_paso3_gananciaOrdinaria.setEditable(false);

        lbl_paso3_valorExtra.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_paso3_valorExtra.setForeground(new java.awt.Color(255, 0, 51));
        lbl_paso3_valorExtra.setText("Valor extraordinaria");

        jLabel26.setText("-");

        jLabel27.setText("=");

        jLabel28.setText("* 75% (tarifa BCE) ");

        lbl_paso3_impuestoTOTAL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_paso3_impuestoTOTAL.setForeground(new java.awt.Color(51, 0, 51));
        lbl_paso3_impuestoTOTAL.setText("Valor extraordinaria");

        lbl_paso3_valorExtra2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_paso3_valorExtra2.setForeground(new java.awt.Color(51, 0, 51));
        lbl_paso3_valorExtra2.setText("IMPUESTO TOTAL A PAGAR:");

        javax.swing.GroupLayout panel_paso3Layout = new javax.swing.GroupLayout(panel_paso3);
        panel_paso3.setLayout(panel_paso3Layout);
        panel_paso3Layout.setHorizontalGroup(
            panel_paso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_paso3Layout.createSequentialGroup()
                .addGroup(panel_paso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_paso3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel_paso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_paso3Layout.createSequentialGroup()
                                .addComponent(txt_paso3_ValorBienConIntereses, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_paso3_FranjaExenta, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17))
                            .addComponent(jLabel22)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_paso3Layout.createSequentialGroup()
                                .addComponent(txt_paso3_valorVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_paso3_gananciaOrdinaria, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)))
                        .addGap(20, 20, 20)
                        .addComponent(lbl_paso4))
                    .addGroup(panel_paso3Layout.createSequentialGroup()
                        .addGroup(panel_paso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_paso3Layout.createSequentialGroup()
                                .addGap(224, 224, 224)
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl_paso3_valorExtra2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(panel_paso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_paso3_valorExtra)
                            .addComponent(lbl_paso5)
                            .addComponent(lbl_paso3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_paso3_impuestoTOTAL, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_paso3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel28)
                .addGap(57, 57, 57))
        );
        panel_paso3Layout.setVerticalGroup(
            panel_paso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_paso3Layout.createSequentialGroup()
                .addGroup(panel_paso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(lbl_paso4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_paso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_paso3_ValorBienConIntereses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_paso3_FranjaExenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_paso3))
                .addGap(23, 23, 23)
                .addGroup(panel_paso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_paso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_paso3_gananciaOrdinaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_paso3_valorVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_paso3_valorExtra))
                    .addGroup(panel_paso3Layout.createSequentialGroup()
                        .addComponent(lbl_paso5)
                        .addGap(21, 21, 21)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel28)
                .addGap(18, 18, 18)
                .addGroup(panel_paso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_paso3_impuestoTOTAL)
                    .addComponent(lbl_paso3_valorExtra2))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(panel_paso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_paso2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_paso3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_paso3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panel_paso1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panel_paso2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jLabel24.setText("+");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(386, 386, 386)
                    .addComponent(jLabel24)
                    .addContainerGap(475, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(277, 277, 277)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(286, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_tiempoAniosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tiempoAniosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tiempoAniosActionPerformed

    private void btn_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcularActionPerformed
        // TODO add your handling code here:
        
        if(txt_valorVenta.getText().equalsIgnoreCase("") || txt_valorVenta.getText().equalsIgnoreCase("0") ){
            JOptionPane.showMessageDialog(null, "Ingrese valor de venta");
            return;
        }
        
        BigDecimal valor_compra = new BigDecimal(txt_valorCosto.getText());
        BigDecimal valor_mejoras = new BigDecimal(txt_valorMejoras.getText());
        BigDecimal valor_contribucionesEspeciales = new BigDecimal(txt_valorContribucionesEspeciales.getText());
        BigDecimal valor_totalBien = new BigDecimal(BigInteger.ZERO);

        valor_totalBien = valor_compra.add(valor_mejoras).add(valor_contribucionesEspeciales);
        txt_paso1.setText("" + valor_totalBien);
        panel_paso1.setVisible(true);
        jPanel4.setVisible(true);
        panel_paso2.setVisible(false);
        panel_paso3.setVisible(false);

    }//GEN-LAST:event_btn_calcularActionPerformed

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here:
        FA_formula formula = new FA_formula();
        formula.setAlwaysOnTop(true);
        formula.setVisible(true);
    }//GEN-LAST:event_jLabel18MouseClicked

    private void btn_paso2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_paso2ActionPerformed
        // TODO add your handling code here:
        BigDecimal valor_totalBien = new BigDecimal(txt_paso1.getText());
        Double valorFactorAjuste = obtenerFactorDeAjuste(Double.parseDouble(txt_tiempoAnios.getText()), Double.parseDouble(txt_tiempoMeses.getText()));

        txt_paso2_ValorBien.setText(txt_paso1.getText());
        txt_paso2_FA.setText("" + valorFactorAjuste);

        BigDecimal valor_totalBienConInteres = new BigDecimal(BigInteger.ZERO);
        valor_totalBienConInteres = valor_totalBien.multiply(new BigDecimal(valorFactorAjuste));

        valor_totalBienConInteres = valor_totalBienConInteres.setScale(2, BigDecimal.ROUND_HALF_UP);

        lbl_paso2.setText("" + valor_totalBienConInteres);
        panel_paso2.setVisible(true);
    }//GEN-LAST:event_btn_paso2ActionPerformed

    private void btn_paso3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_paso3ActionPerformed
        // TODO add your handling code here:
        txt_paso3_ValorBienConIntereses.setText(lbl_paso2.getText());
        txt_paso3_FranjaExenta.setText(txt_FranjaExenta.getText());
        BigDecimal valor_paso3 = new BigDecimal(BigInteger.ZERO);
        valor_paso3 = valor_paso3.add(new BigDecimal(txt_paso3_ValorBienConIntereses.getText()));
        valor_paso3 = valor_paso3.add(new BigDecimal(txt_paso3_FranjaExenta.getText()));
        lbl_paso3.setText("" + valor_paso3);

        txt_paso3_valorVenta.setText(txt_valorVenta.getText());
        txt_paso3_gananciaOrdinaria.setText(lbl_paso3.getText());
        Double valorExtra = Double.parseDouble(txt_paso3_valorVenta.getText()) - Double.parseDouble(txt_paso3_gananciaOrdinaria.getText());

        lbl_paso3_valorExtra.setText("" + round(valorExtra, 2));
        valorExtra = valorExtra * 0.75;
        lbl_paso3_impuestoTOTAL.setText("" + round(valorExtra, 2));

        if (valorExtra < 0) {
            lbl_paso3_impuestoTOTAL.setText("0");
        }
        panel_paso3.setVisible(true);
    }//GEN-LAST:event_btn_paso3ActionPerformed

    public static double round(Double value, int places) {
        if (places < 0) {
            throw new IllegalArgumentException();
        }

        long factor = (long) Math.pow(10, places);
        value = value * factor;
        long tmp = Math.round(value);
        return (double) tmp / factor;
    }

    private Double obtenerFactorDeAjuste(Double anios, Double meses) {
        Double valor_TasaBCE = Double.parseDouble(txt_TasaPasivaBCE.getText());
        valor_TasaBCE = valor_TasaBCE / 100;
        Double totalMeses = (anios * 12) + meses;
        Double n = totalMeses / 12;
        Double valorFactorAjuste;
        valorFactorAjuste = Math.pow((1 + valor_TasaBCE), n);
        return valorFactorAjuste;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFmain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_calcular;
    private javax.swing.JButton btn_paso2;
    private javax.swing.JButton btn_paso3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbl_paso2;
    private javax.swing.JLabel lbl_paso3;
    private javax.swing.JLabel lbl_paso3_impuestoTOTAL;
    private javax.swing.JLabel lbl_paso3_valorExtra;
    private javax.swing.JLabel lbl_paso3_valorExtra2;
    private javax.swing.JLabel lbl_paso4;
    private javax.swing.JLabel lbl_paso5;
    private javax.swing.JPanel panel_paso1;
    private javax.swing.JPanel panel_paso2;
    private javax.swing.JPanel panel_paso3;
    private javax.swing.JTextField txt_FranjaExenta;
    private javax.swing.JTextField txt_SBU;
    private javax.swing.JTextField txt_TasaPasivaBCE;
    private javax.swing.JTextField txt_paso1;
    private javax.swing.JTextField txt_paso2_FA;
    private javax.swing.JTextField txt_paso2_ValorBien;
    private javax.swing.JTextField txt_paso3_FranjaExenta;
    private javax.swing.JTextField txt_paso3_ValorBienConIntereses;
    private javax.swing.JTextField txt_paso3_gananciaOrdinaria;
    private javax.swing.JTextField txt_paso3_valorVenta;
    private javax.swing.JTextField txt_tiempoAnios;
    private javax.swing.JTextField txt_tiempoMeses;
    private javax.swing.JTextField txt_valorContribucionesEspeciales;
    private javax.swing.JTextField txt_valorCosto;
    private javax.swing.JTextField txt_valorMejoras;
    private javax.swing.JTextField txt_valorVenta;
    // End of variables declaration//GEN-END:variables
}
